
  CREATE TABLE FX_PROD
   (	PROD_ID VARCHAR2(15 BYTE) NOT NULL ENABLE, 
        PROD_NM VARCHAR2(15 BYTE),
        PROD_PRICE NUMBER(15,0),
        PROD_BUYER VARCHAR2(15 BYTE),
        PROD_DETAIL VARCHAR2(600 BYTE)
    );