  CREATE TABLE FX_MEMBER
   (	MEM_ID VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	MEM_PASS VARCHAR2(15 BYTE), 
	MEM_NAME VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	MEM_BIR VARCHAR2(15 BYTE), 
	MEM_ADD VARCHAR2(100 BYTE)
   ) ;